name: abu_share_ride
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.28.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  email_validator: '^2.1.16'
  intl_phone_field: ^3.1.0
  firebase_auth: ^4.19.1
  firebase_database: ^10.5.1
  firebase_storage: ^11.7.1
  # firebase_messaging: ^14.8.1
  fluttertoast: ^8.2.4
  # geolocator: ^11.0.0
  geocoder2: ^1.4.0
  # flutter_geofire: ^2.0.3
  flutter_polyline_points: ^1.0.0
  location: ^6.0.1
  smooth_star_rating_nsafe: ^1.0.0+1
  animated_text_kit: ^4.2.2
  # flutter_mapbox_navigation: ^0.1.3
  mapbox_gl: ^0.16.0 
  flutter_dotenv: ^5.0.2
  dio: ^5.4.3+1
  flutter_rating_bar: ^4.0.0
  # google_fonts: ^2.3.1
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.0.4

  
  # user_repository:
  #  path: packages/user_repository

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#84f071"



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/config/